### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by JessicaMulein** [gnabgib/gnablib-ts#6]
[edit: deleted]

**Comment by r3-m** [comment]
A big documentation push is on our radar, sorry about that.  The repo (here) doesn't have `dist` (compiled - useful for dev) or `release` (minimized for prod) folders, they are only built on deploy (to npm) or locally using `npm build` (`pnpm`, `yarn`)).  The pieces are namespaced, and not imported into the root namespace.  In order to use them you should import from those namespaces.  

Right now the test code (`tst/*`) is probably the best place to see how to use components.  (Although note they use relative imports so, for example `tst/checksum/adler.test.ts` imports `import {adler32} from '../../src/checksum';` which would be `import {adler32} from 'gnablib/checksum';` in a production project).   I know that's not a very helpful answer (we're working on docs/the test code might help).  Which aspect were you looking to use? - perhaps we can prioritise that documentation.
